import 'dotenv/config';
import ms from 'ms';

export const config = {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT || 5001,

  // DATABASE
  MONGO_URI: process.env.MONGO_URI,

  // GOOGLE
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,

  // NODEMAILER
  NODEMAILER_HOST: process.env.NODEMAILER_HOST,
  NODEMAILER_PORT: process.env.NODEMAILER_PORT,
  NODEMAILER_USERNAME: process.env.NODEMAILER_USERNAME,
  NODEMAILER_PASSWORD: process.env.NODEMAILER_PASSWORD,

  // JWT
  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,

  // OTHERS
  JWT_ACCESS_TOKEN_AGE: ms('15m'),
  JWT_REFRESH_TOKEN_AGE: ms('24h'),
  EMAIL_VERIFICATION_TOKEN_AGE: ms('30m'),
  PASSWORD_RESET_TOKEN_AGE: ms('30m'),
};
